name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Start React app
      run: npm start & 
      env:
        CI: false

    - name: Wait for app to start
      run: |
        echo "Waiting for app to start..."
        sleep 30

    - name: Run Selenium tests
      run: npm test
      env:
        SELENIUM_BROWSER: chrome
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: iPlant-tests-report/