name: SonarQube
on:
  push:
    branches:
      - main
jobs:
  build:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Start the application in the background
      - name: Start application
        run: |
          npm start & 
          sleep 30 # Give the server some time to start

      # Run Cypress tests with specific spec file
      - name: Run Cypress tests
        run: |
          npx cypress run --spec "cypress/e2e/spec.cy.js"

      # Run SonarQube scan
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}